### ISSUE TITLE
router script addition

### ISSUE THREAD

**Issue by bqtran** [brapifra/vscode-phpserver#13]
Thanks for the extension! Are you able to add in an additional parameter for a router script? (See https://secure.php.net/manual/en/features.commandline.webserver.php , Example 3) I tried to define a file within the relativePath parameter ( "relativePath": "foo .htrouter.php"), but the extension would immediately die everytime I tried to start the server, so for a workaround I have to start the server manually in the terminal instead.

Normally the command would look something similar like this: "php -S localhost:8000 -t foo/ .htrouter.php"

Thanks again.

**Comment by brapifra** [comment]
The extension uses a [router script ](https://github.com/brapifra/vscode-phpserver/blob/master/src/logger.php) in order to log the requests (Only in Windows platforms, in Linux/OSx systems is not necessary). So if I add this new option, the extension won't log the requests (again, only in windows platforms) unless the script includes a logging functionality. What do you think? Is it worth it?

**Comment by bqtran** [comment]
You could put the script into the readme for windows users to integrate the request logging into their router script in case they want to keep the functionality. Otherwise, I'd say keep it consistent across all platforms and give people the ability to write their own router scripts in windows as well.  Thoughts? :)

**Comment by brapifra** [comment]
Done! :)
