### ISSUE TITLE
La extensión no funcionan con php v5.3

### ISSUE THREAD

**Issue by AlexanderMz** [brapifra/vscode-phpserver#18]

**Comment by brapifra** [comment]
Podrías dar más detalles?

**Comment by AlexanderMz** [comment]
![image](https://user-images.githubusercontent.com/12861422/33211547-0b4b297e-d0ed-11e7-947d-0c2a4e5ff1c6.png)

Esto es lo que imprime vscode, leí que php 5.6 hacia atrás php no cuenta con servidor para desarrollo, se utiliza php-cgi

**Comment by brapifra** [comment]
Así es, al parecer esta opción se incluye desde php 5.4.0
¿Necesitas realmente usar esta versión de php? Porque no veo una solución sencilla a este problema

**Comment by AlexanderMz** [comment]
No te preocupes, me toco migrar el proyecto
Gracias de todas formas!

**Comment by FireSBurnsmuP** [comment]
I had this issue too, and figured I'd include an English summary of what happened here for posterity and search-engine indexing:
For the record - not Spanish speaking; used google translate to get what I couldn't glean from French speaking.

If you're getting the PHP usage text in your output window when attempting to run the server, then you're using a version of PHP which doesn't have the development server option built-in.
You're going to have a hard time using this development server plugin with any versions before 5.6 (or perhaps 5.4) when they started including the development server this plugin uses.

Since I'm trying to support something using 5.3 in production (I know - shoot me now), I guess I'm out of luck with this plugin, but I'm sure it's awesome when you can use it!
