### ISSUE TITLE
Can't run on other files than index.php

### ISSUE THREAD

**Issue by BaldEagleBird** [brapifra/vscode-phpserver#22]
Hi,
whenever I click on "Start Project with PHP" it runs it on index.php and not on a file I want it to run. Is it possible to point it to a different file?
Thanks!

**Comment by brapifra** [comment]
You can change it in the url. For example:

`http://localhost:3000/index2.php` will show you the index2.php.

If what you want is to change the default php file that will be shown when you enter `http://localhost:3000`, and you find this feature really useful, I could add it.

**Comment by BaldEagleBird** [comment]
Thank you @brapifra. 
No need to change the default php file, I'll just modify the url.

**Comment by jimbien** [comment]
big thank you

**Comment by sdbxsdb** [comment]
I've got a similar issue and I can change the URL no problem BUT I have several websites with the same URLs and paths (contact, about etc etc so I can only load up the page that the server had last.  I reallllllly don't want to have to clear my browers cache each time because.. pain in the ass.   Any suggestions?

**Comment by w2leo** [comment]
> If what you want is to change the default php file that will be shown

Hi! But how can I change default file? Or, the another answer, where I can configure default folder for PHP server extention in VS Code?

**Comment by capitanumihai** [comment]
For ex root_address/folder/name_of_the_php_file.php
