### ISSUE TITLE
ATTENTION: Threat Blocked. logger.php was infected with IDP.Generic

### ISSUE THREAD

**Issue by surjithctly** [brapifra/vscode-phpserver#75]
![image](https://user-images.githubusercontent.com/1884712/82986332-49ba7280-a013-11ea-9280-33e50bffd814.png)

Logger.php was blocked by Antivirus since its infected with virus. Please take immediate action.

~Surjith

**Comment by korpow** [comment]
I am no security expert, but looking at the [file in question](https://github.com/brapifra/vscode-phpserver/blob/master/src/logger.php) it seems to be a harmless script for logging as the name implies.

One of the first results of a search for IDP.Generic had this to say:
>The IDP in this virus stands for Identity Detection Protection. It references the fact that the virus attempts to steal information related to your identity-

Makes sense so stuff like keystroke and user telemetry **loggers**.
> The IDP.Generic warning is most often a byproduct of an outdated version of AVG or Avast antivirus software and can be easily removed just by updating that software.

I'd say knowing this and the above, and seeing that a "Behavior Shield" triggered this, if updating the AV does not work just exclude the file.

**Comment by surjithctly** [comment]
> just exclude the file.
I tried to Move it to virus chest, but the code doesn't work without it. Shows PHP error.

**Comment by korpow** [comment]
If the file is now missing instead of exempted from your AV it makes sense that you would be getting an error if you also have not configured a custom router.

This is because [under the hood](https://github.com/brapifra/vscode-phpserver/blob/84c258c9731c4e09de04f86c714fdc00b2786cd9/src/Server.ts#L84) php is being passed args to launch its [built in server](https://www.php.net/manual/en/features.commandline.webserver.php) with what is now a bad argument for the router.

The workaround then should be to make a dummy router.php like below and configure the `phpserver.router` setting to use it.
```php
// router.php
<?php
return false;
?>
```
Be sure to note the disclaimer present in the README:
> If a custom router script is used on a Windows platform, there will be no console output unless a logger like [the file in question](https://github.com/brapifra/vscode-phpserver/blob/master/src/logger.php) is included in the script.

**Comment by brapifra** [comment]
As @korpow pointed out, I don't think this is due to the extension itself. I did a quick google search and it looks like other people has had problems with php's built-in server and avast: https://superuser.com/questions/1378309/avast-detects-php-built-in-web-server-as-a-virus
