### ISSUE TITLE
Where to put php.ini / default path?

### ISSUE THREAD

**Issue by Kalaschnik** [brapifra/vscode-phpserver#83]
I know that I can config `phpserver.phpConfigPath` and it states that _Path to php.ini file. If empty, the extension uses the default path._ However, what/where is the default path the extension expects the `php.ini`to be?

Got it; `/etc/php.ini`

It would be cool if users were able to put a `php.ini`in the root of their current working directory which would override the system’s defaults.

**Comment by jesperlind** [comment]
Sorry if I hijack this issue. Perhaps someone can help my.

I want to increase upload_max_filesize since its only 2M
Checked in /etc and there was only a php.ini.default in there. 
I copied it to php.ini and edited upload_max_filesize = 5M
The path is set to this php.ini but upload_max_filesize is still 2M

Any ideas?
